# RoRoRo Ur Task — install Claude Code hooks as git pre-commit hooks.
# Run from repo root: powershell -ExecutionPolicy Bypass -File .claude/hooks/install.ps1
# Use -Force to overwrite an existing .git/hooks/pre-commit.

param(
  [switch]$Force
)

$ErrorActionPreference = 'Stop'

# Resolve repo root from this script's location: .claude/hooks/install.ps1 -> ../../
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$gitDir = Join-Path $repoRoot '.git'

if (-not (Test-Path $gitDir)) {
  Write-Host "Not a git repository (no .git/ at $repoRoot)." -ForegroundColor Red
  Write-Host "Run 'git init' first, then re-run this installer." -ForegroundColor Red
  exit 1
}

$hookPath = Join-Path $gitDir 'hooks\pre-commit'
$hookSource = @'
#!/usr/bin/env bash
# Generated by .claude/hooks/install.ps1 — do not edit by hand.
# Edit .claude/hooks/pre-commit-*.sh and re-run install.ps1 -Force.

set -e

repoRoot=$(git rev-parse --show-toplevel)

bash "$repoRoot/.claude/hooks/pre-commit-secret-scan.sh"
bash "$repoRoot/.claude/hooks/pre-commit-local-path-guard.sh"
'@

if ((Test-Path $hookPath) -and -not $Force) {
  Write-Host "$hookPath already exists. Re-run with -Force to overwrite." -ForegroundColor Yellow
  exit 1
}

# Write with LF line endings — Git Bash on Windows requires Unix line endings for hooks to be POSIX-clean.
[System.IO.File]::WriteAllText($hookPath, $hookSource.Replace("`r`n", "`n"))

Write-Host "Installed $hookPath" -ForegroundColor Green
Write-Host ""
Write-Host "Verify with a test commit. To debug a failing hook in isolation:" -ForegroundColor Cyan
Write-Host "  bash .claude/hooks/pre-commit-secret-scan.sh"
Write-Host "  bash .claude/hooks/pre-commit-local-path-guard.sh"
